// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
// 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
// whose values do not exceed four million, find the sum of the even-valued
// terms.

#include <iostream>
#include <vector>

using namespace std;

int main() {
  int maxval = 4000000;
  int sum = 0;
  vector<int> fibonacci{1, 2};

  while (*fibonacci.rbegin() < maxval) {
    fibonacci.push_back(*(fibonacci.rbegin() + 1) + *(fibonacci.rbegin()));
  }
  fibonacci.pop_back();

  for (auto i : fibonacci) {
    if (i % 2 == 0) {
      sum += i;
    }
  }

  cout << sum << "\n";
  return 0;
}